import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Navbar from '@/components/Navbar';
import "slick-carousel/slick/slick.css";
import Footer from '@/components/Footer';
import SessionLayout from '@/components/SessionLayout';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen font-sens antialiased bgDesign", inter.className)}>
        <SessionLayout>
          <Navbar/>
          {children}
          <Footer/>
        </SessionLayout>
      </body>
    </html>
  )
}
